# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('published_date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('wordpress_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('published_date', models.DateField(default=None)),
                ('archived_articles', models.ManyToManyField(to='similarity.ArchivedArticle')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='similarity.ArticleContent')),
            ],
        ),
        migrations.AddField(
            model_name='archivedarticle',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='similarity.ArticleContent'),
        ),
    ]
