# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontent',
            name='wordpress_id',
        ),
        migrations.AddField(
            model_name='archivedarticle',
            name='wordpress_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentarticle',
            name='wordpress_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
