# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('similarity', '0002_auto_20160201_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedarticle',
            name='veridian_id',
            field=models.CharField(default=datetime.datetime(2016, 2, 7, 5, 9, 13, 541538, tzinfo=utc), max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='author',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
