# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarity', '0003_auto_20160207_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='author',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
